"""Module to interact with Knowledge Models.

This module contains class to interact with Knowledge Models in Studio.

Typical usage example:

    ```python
    knowledge_model = package.get_knowledge_model(ANALYSIS_ID)
    knowledge_model = package.create_knowledge_model(content)
    knowledge_model.delete()
    ```
"""
import logging
import typing

from pycelonis.ems.studio.content_node import ContentNode
from pycelonis.ems.studio.content_node.knowledge_model.component import Filter, Record
from pycelonis.ems.studio.content_node.knowledge_model.content import KnowledgeModelContent
from pycelonis.errors import PyCelonisQueryResolutionError
from pycelonis.pql.pql import PQL
from pycelonis.service.integration.service import DataQuery, QueryEnvironment
from pycelonis.service.semantic_layer.service import (
    DataCommand,
    DataCommandBatchRequest,
    DataCommandBatchTransport,
    FinalModelOptions,
    LayerComputeTransport,
    QueryRequest,
    SemanticLayerService,
)
from pycelonis_core.utils.errors import PyCelonisValueError

logger = logging.getLogger(__name__)


class KnowledgeModel(ContentNode):
    """Knowledge model object to interact with knowledge model specific studio endpoints."""

    def get_content(
        self,
        with_variable_replacement: bool = True,
        with_autogenerated_data_model_data: bool = True,
        with_default_values: bool = True,
        validate_pql: bool = True,
        with_unknown_variables_validation: bool = True,
    ) -> typing.Optional["KnowledgeModelContent"]:
        """Returns content of knowledge model.

        Args:
            with_variable_replacement: Specifies if variables are replaced by their values in knowledge model.
            with_autogenerated_data_model_data: Specifies whether auto generated KPIs and records for data model
                should be added to content.
            with_default_values: Specifies if default values are added to content.
            validate_pql: Specifies if PQLs in knowledge model are validated.
            with_unknown_variables_validation: Specifies if unknown variables are validated.

        Returns:
            Knowledge model content.

        Examples:
            Extract data based on PQLs from knowledge model:
            ```python
            from pycelonis.pql import PQL, PQLColumn

            record = knowledge_model.get_content().records.find_by_id('ACTIVITIES')
            attribute = record.attributes.find_by_id('ACTIVITY_EN')

            query = PQL() + attribute.get_column()

            data_query, query_environment = knowledge_model.resolve_query(query)
            df = data_model.export_data_frame(data_query, query_environment)
            ```
        """
        final_layer_transport = SemanticLayerService.post_api_layer_id_name_final(
            self.client,
            self.root_with_key,
            FinalModelOptions(
                with_variable_replacement=with_variable_replacement,
                with_autogenerated_data_model_data=with_autogenerated_data_model_data,
                with_default_values=with_default_values,
                validate_pql=validate_pql,
                with_unknown_variables_validation=with_unknown_variables_validation,
            ),
        )
        if final_layer_transport.layer is None:
            return None
        return KnowledgeModelContent.from_transport(final_layer_transport.layer)

    def resolve_query(
        self, query: PQL, draft: bool = True, **kwargs: typing.Any
    ) -> typing.Tuple[DataQuery, typing.Optional[QueryEnvironment]]:
        """Returns Data Query and Query environment for a knowledge model.

        Use this method to resolve queries that are based on Knowledge Model content.
        The returned DataQuery and QueryEnvironment can than be used to query data via
        [DataModel.export_data_frame][pycelonis.ems.data_integration.data_model.DataModel.export_data_frame].

        Args:
            query: PQL query to be resolved.
            draft: If true, uses draft of knowledge model, if false uses published version.
            **kwargs: Key word arguments are passed to `get_content` function.

        Returns:
            Returns Data Query and Query environment.

        Examples:
            Extract data based on PQLs from knowledge model:
            ```python
            from pycelonis.pql import PQL, PQLColumn

            record = knowledge_model.get_content().records.find_by_id('ACTIVITIES')
            attribute = record.attributes.find_by_id('ACTIVITY_EN')

            query = PQL() + attribute.get_column()

            data_query, query_environment = knowledge_model.resolve_query(query)
            df = data_model.export_data_frame(data_query, query_environment)
            ```
        """
        layer = self.get_content(**kwargs)

        if layer is None:
            raise PyCelonisValueError("Can't resolve query. Knowledge model content is empty.")

        batch_request = DataCommandBatchRequest(
            variables=self._get_variables(layer),
            requests=[DataCommandBatchTransport(request=DataCommand(commands=[DataQuery(queries=query.queries)]))],
        )

        query_request = QueryRequest(batch_request=batch_request, filters=None)

        layer_compute_transport = LayerComputeTransport(
            layer=layer,
            request=query_request,
            draft=draft,
        )

        post_batch_query_transport = SemanticLayerService.post_api_knowledge_model_resolve_query(
            self.client, layer_compute_transport
        )

        knowledge_model_commands = post_batch_query_transport.analysis_commands or []
        if len(knowledge_model_commands) != 1 or knowledge_model_commands[0] is None:
            raise PyCelonisQueryResolutionError("Not the correct number of knowledge model commands resolved")

        request = knowledge_model_commands[0].request or DataCommand()
        commands = request.commands or []
        if len(commands) != 1 or commands[0] is None:
            raise PyCelonisQueryResolutionError("Not the correct number of knowledge model commands resolved")

        if not post_batch_query_transport.query_environment:
            raise PyCelonisQueryResolutionError("No query environment resolved")

        return DataQuery(**commands[0].json_dict()), QueryEnvironment(
            **post_batch_query_transport.query_environment.json_dict()
        )

    def _get_variables(self, content: "KnowledgeModelContent") -> typing.List[typing.Dict]:
        return [
            {"name": variable.id, "type": "text_replacement", "value": variable.value}
            for variable in content.variables or []
            if variable is not None
        ]

