from setuptools import setup, find_packages

setup(
    name='pycelonis',
    version='2.20.1',
    packages=find_packages(),
    install_requires=[
        'pycelonis_core==2.10.3',
        'httpx>=0.28.0',
        'pydantic>=2.0.0',
        'pandas',
        'pyarrow',
        'numpy',
        'python-dateutil',
        'pytz',
        'PyYAML',
        'saolapy',
        'annotated-types',
        'anyio',
        'certifi',
        'colorama',
        'h11',
        'httpcore',
        'idna',
        'packaging',
        'six'
    ],
    python_requires='>=3.8',
)